[ -a $HOME/.Xresources ] && xrdb -merge .Xresources

# VMWare Tools
VMWARE_SETUID_TOOLS=/usr/lib/vmware-tools/bin/vmware-user-suid-wrapper
[ -u $VMWARE_SETUID_TOOLS ] && $VMWARE_SETUID_TOOLS

# HipChat
HIPCHAT=/opt/HipChat/bin/HipChat
[ -x $HIPCHAT ] && $HIPCHAT &

eval $(gnome-keyring-daemon --start)
export GNOME_KEYRING_CONTROL
export GNOME_KEYRING_PID
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_SOCKET

# nice dark purple
xsetroot -solid rgb:30/00/38

# need to rejigger network sometimes
nm-applet &

exec awesome --config $HOME/.config/awesome/rc.lua >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr
