[[ -a $HOME/.Xresources ]] && xrdb -merge $HOME/.Xresources

# VMWare Tools
VMWARE_SETUID_TOOLS=/usr/lib/vmware-tools/bin/vmware-user-suid-wrapper
[[ -u "$VMWARE_SETUID_TOOLS" ]] && "$VMWARE_SETUID_TOOLS"

# HipChat
HIPCHAT=$(which hipchat)
[[ -x "$HIPCHAT" ]] || HIPCHAT=/opt/HipChat/bin/hipchat
[[ -x "$HIPCHAT" ]] && "$HIPCHAT" &

# Keyring
eval $(gnome-keyring-daemon --start)
export GNOME_KEYRING_CONTROL
export GNOME_KEYRING_PID
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_SOCKET

# Screen settings
xsetroot -solid rgb:30/00/38
xscreensaver -no-splash &

GSD=$(which gnome-settings-daemon)
[[ -x "$GSD" ]] && "$GSD" &

# need to rejigger network sometimes
nm-applet &

GVM=$(which gnome-volume-manager)
[[ -x "$GVM" ]] && "$GVM" &

# Dropbox
# [ -x $HOME/.dropbox-dist/dropboxd ] && $HOME/.dropbox-dist/dropboxd &

# Conky
CONKY=$(which conky)
[[ -x "$CONKY" ]] && "$CONKY"  # auto-backgrounds itself

# User-local paths to support Super-R
[[ -d $HOME/local/bin ]] && export PATH=$PATH:$HOME/local/bin

# trick Java apps into thinking awesome is a reparenting window manager.
# Also, for some unfathomable reason HipChat likes to set the window manager name to itself...
wmname LG3D 2>&1 >> /dev/null

[[ -d $HOME/.cache/awesome ]] || mkdir -p $HOME/.cache/awesome
exec awesome --config $HOME/.config/awesome/rc.lua >> $HOME/.cache/awesome/stdout 2>> $HOME/.cache/awesome/stderr
