[ -a $HOME/.Xresources ] && xrdb -merge .Xresources

# VMWare Tools
VMWARE_SETUID_TOOLS=/usr/lib/vmware-tools/bin/vmware-user-suid-wrapper
[ -u $VMWARE_SETUID_TOOLS ] && $VMWARE_SETUID_TOOLS

# HipChat
HIPCHAT=/opt/HipChat/bin/HipChat
[ -x $HIPCHAT ] && $HIPCHAT &

# Keyring
eval $(gnome-keyring-daemon --start)
export GNOME_KEYRING_CONTROL
export GNOME_KEYRING_PID
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_SOCKET

# Screen settings
xsetroot -solid rgb:30/00/38
xscreensaver &

# need to rejigger network sometimes
nm-applet &

[ -d $HOME/.cache/awesome ] || mkdir -p $HOME/.cache/awesome
exec awesome --config $HOME/.config/awesome/rc.lua >> $HOME/.cache/awesome/stdout 2>> $HOME/.cache/awesome/stderr
