xrdb -merge .Xresources

trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent true --tint 0x191970 --height 12 &

# VMWare Tools
VMWARE_SETUID_TOOLS=/usr/lib/vmware-tools/bin/vmware-user-suid-wrapper
[ -u $VMWARE_SETUID_TOOLS ] && $VMWARE_SETUID_TOOLS

# HipChat
HIPCHAT=/opt/HipChat/bin/HipChat
[ -x $HIPCHAT ] && $HIPCHAT &

# nice dark purple
xsetroot -solid rgb:30/00/38

exec xmonad
