xrdb -merge .Xresources

trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent true --tint 0x191970 --height 12 &

# VMWare Tools
VMWARE_SETUID_TOOLS=/usr/lib/vmware-tools/bin/vmware-user-suid-wrapper
if [ -u $VMWARE_SETUID_TOOLS ]; then
    $VMWARE_SETUID_TOOLS
fi

exec xmonad
